package com.redhat.cajun.navy.cajun_navy_processes;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GetRespondersResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public GetRespondersResponse() {
    }




}